allowBuilds:
  '@stellar/stellar-sdk': true
  blake-hash: true
  bufferutil: true
  esbuild: false
  protobufjs: true
  sharp: false
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
  workerd: false
